import{CopyEngine}from'./degradation-engine.js?v=20260809-3';
const $=s=>document.querySelector(s),engine=new CopyEngine(),source=$('#sourceCanvas'),result=$('#resultCanvas');let current=null,generation=0,selections=[],activeSelection=-1,pendingRange=null,previousText=$('#text').value;
const typeDefs=[['size','SIZE',94,24,180,'px'],['leading','LEADING',92,70,150,'%'],['tracking','TRACKING',0,-8,30,'px'],['width','WIDTH',980,500,1400,'px'],['padding','PADDING',90,20,220,'px']];
const machineDefs=[['threshold','CONTRAST / THRESHOLD',53,0,100,''],['tonerDensity','TONER DENSITY',58,0,100,''],['inkBleed','INK BLEED',22,0,100,''],['cornerRoundness','CORNER ROUNDNESS',28,0,100,''],['erosion','EROSION',12,0,100,''],['dropout','DROPOUT',16,0,100,''],['edgeRoughness','EDGE ROUGHNESS',27,0,100,''],['grain','GRAIN',24,0,100,''],['localDistortion','LOCAL DISTORTION',10,0,100,''],['characterFailure','CHARACTER FAILURE',8,0,100,''],['copyCount','GENERATIONAL COPY COUNT',1,1,8,'×']];
const selectionDefs=[['selectionBulb','BULB / WEIGHT',35,0,100,''],['selectionErosion','ERODE / THIN',0,0,100,''],['selectionDamage','LOCAL DAMAGE',18,0,100,''],['selectionKerning','KERNING',0,-30,80,'px']];
function controls(target,defs){target.innerHTML=defs.map(([id,label,val,min,max,unit])=>`<label class="slider-row" for="${id}"><span>${label}</span><input id="${id}" type="range" min="${min}" max="${max}" value="${val}"><output id="${id}Out">${val}${unit}</output></label>`).join('');defs.forEach(([id,,, , ,unit])=>$('#'+id).addEventListener('input',e=>{$('#'+id+'Out').value=e.target.value+unit;if(typeDefs.some(d=>d[0]===id))renderSource();if(selectionDefs.some(d=>d[0]===id)){if(activeSelection>=0){selections[activeSelection].bulb=val('selectionBulb');selections[activeSelection].erosion=val('selectionErosion');selections[activeSelection].damage=val('selectionDamage');selections[activeSelection].kerning=val('selectionKerning');renderSelections()}renderSource()}}))}
controls($('#typeControls'),typeDefs);controls($('#machineControls'),machineDefs);controls($('#selectionControls'),selectionDefs);
function val(id){return Number($('#'+id).value)}function options(pass){return{seed:$('#seed').value||'copyshop',pass,threshold:val('threshold'),contrast:val('threshold'),tonerDensity:val('tonerDensity'),inkBleed:val('inkBleed'),cornerRoundness:val('cornerRoundness'),erosion:val('erosion'),dropout:val('dropout'),edgeRoughness:val('edgeRoughness'),grain:val('grain'),localDistortion:val('localDistortion'),characterFailure:val('characterFailure')}}
function treatmentAt(index){if(pendingRange&&index>=pendingRange.start&&index<pendingRange.end)return{bulb:val('selectionBulb'),erosion:val('selectionErosion'),damage:val('selectionDamage'),kerning:val('selectionKerning'),font:$('#selectionFont').value,key:'pending'};const found=selections.findLast?selections.findLast(s=>index>=s.start&&index<s.end):[...selections].reverse().find(s=>index>=s.start&&index<s.end);return found?{...found,key:selections.indexOf(found)}:null}
function charFont(index,baseFont){const treatment=treatmentAt(index);return treatment&&treatment.font&&treatment.font!=='inherit'?treatment.font:baseFont}
function measureChar(ctx,item,size,baseFont){ctx.font=`900 ${size}px "${charFont(item.index,baseFont)}"`;return ctx.measureText(item.char).width}
function wrapText(ctx,text,maxWidth,tracking,size,baseFont){const lines=[];let line=[];for(let i=0;i<text.length;){if(text[i]==='\n'){lines.push(line);line=[];i++;continue}const match=text.slice(i).match(/^\S+|^ +/),token=match?match[0]:text[i],chars=[...token].map((char,k)=>({char,index:i+k})),candidate=[...line,...chars],measure=candidate.reduce((sum,c)=>sum+measureChar(ctx,c,size,baseFont)+tracking,0)-tracking;if(measure>maxWidth&&line.length&&token.trim()){lines.push(line);line=chars}else line=candidate;i+=token.length}lines.push(line);return lines}
function seededUnit(index,salt=0){let n=(index+1)*2654435761+salt*1597334677;return((n^(n>>>16))>>>0)/4294967295}
function drawTracked(ctx,line,x,y,tracking,align,size,baseFont){const widths=line.map(c=>measureChar(ctx,c,size,baseFont)),adjustments=line.map((item,i)=>{const here=treatmentAt(item.index),next=i<line.length-1?treatmentAt(line[i+1].index):null;return here&&next&&here.key===next.key?(here.kerning||0):0}),total=widths.reduce((a,b)=>a+b,0)+tracking*Math.max(0,line.length-1)+adjustments.reduce((a,b)=>a+b,0);let cursor=align==='center'?x-total/2:align==='right'?x-total:x;for(let i=0;i<line.length;i++){const item=line[i],w=widths[i],treatment=treatmentAt(item.index);ctx.font=`900 ${size}px "${charFont(item.index,baseFont)}"`;if(treatment){const bulb=treatment.bulb,erosion=treatment.erosion||0,damage=treatment.damage;ctx.save();ctx.lineJoin='round';ctx.lineCap='round';ctx.strokeStyle='#111';ctx.lineWidth=bulb*.12;ctx.strokeText(item.char,cursor,y);ctx.fillText(item.char,cursor,y);if(erosion>0){ctx.strokeStyle='#f6f6f1';ctx.lineWidth=erosion*.14;ctx.strokeText(item.char,cursor,y)}if(damage>0&&item.char.trim()){ctx.fillStyle='#f6f6f1';const holes=Math.floor(damage/16);for(let h=0;h<holes;h++){const rx=cursor+w*(.12+seededUnit(item.index,h)*.76),ry=y+size*(.12+seededUnit(item.index,h+17)*.65),r=Math.max(1,size*damage/1800*(.5+seededUnit(item.index,h+31)));ctx.beginPath();ctx.ellipse(rx,ry,r*1.5,r,0,0,Math.PI*2);ctx.fill()}}ctx.restore()}else ctx.fillText(item.char,cursor,y);cursor+=w+tracking+adjustments[i]}}
function renderSource(){const width=val('width'),pad=val('padding'),size=val('size'),leading=size*val('leading')/100,tracking=val('tracking'),font=$('#font').value,align=$('#align').value,ctx=source.getContext('2d');ctx.font=`900 ${size}px "${font}"`;const lines=wrapText(ctx,$('#text').value,width-pad*2,tracking,size,font),height=Math.max(700,Math.ceil(pad*2+lines.length*leading));source.width=width;source.height=height;ctx.fillStyle='#f6f6f1';ctx.fillRect(0,0,width,height);ctx.fillStyle='#111';ctx.font=`900 ${size}px "${font}"`;ctx.textBaseline='top';const x=align==='center'?width/2:align==='right'?width-pad:pad;lines.forEach((line,i)=>drawTracked(ctx,line,x,pad+i*leading,tracking,align,size,font));$('#dimensions').textContent=`${width} × ${height} PX`;current=null;generation=0;updateMeta('SOURCE READY')}
function copy(useCurrent=false){$('#status').textContent='PROCESSING';requestAnimationFrame(()=>{let input=useCurrent&&current?current:source;const passes=val('copyCount');for(let p=0;p<passes;p++)input=engine.process(input,options(generation+p+1));current=input;result.width=input.width;result.height=input.height;result.getContext('2d').drawImage(input,0,0);generation+=passes;updateMeta(useCurrent?'COPY OF COPY':'COPY COMPLETE')})}
function updateMeta(status){$('#status').textContent=status;$('#generation').textContent=String(generation).padStart(2,'0');$('#seedReadout').textContent=$('#seed').value;$('#resultLabel').textContent=generation?`generation ${generation}`:'awaiting copy'}
function randomize(){machineDefs.forEach(([id,,,min,max,unit])=>{if(id==='copyCount')return;const n=Math.round(min+Math.random()*(max-min));$('#'+id).value=n;$('#'+id+'Out').value=n+unit});$('#seed').value=Math.random().toString(36).slice(2,10);updateMeta('SETTINGS RANDOMIZED')}
function escapeText(value){return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function setTreatmentControls(s){$('#selectionBulb').value=s.bulb;$('#selectionBulbOut').value=s.bulb;$('#selectionErosion').value=s.erosion||0;$('#selectionErosionOut').value=s.erosion||0;$('#selectionDamage').value=s.damage;$('#selectionDamageOut').value=s.damage;$('#selectionKerning').value=s.kerning||0;$('#selectionKerningOut').value=(s.kerning||0)+'px';$('#selectionFont').value=s.font||'inherit'}
function renderSelections(){const text=$('#text').value;$('#selectionList').innerHTML=selections.length?selections.map((s,i)=>`<span class="selection-chip${i===activeSelection?' active':''}" data-edit="${i}" role="button" tabindex="0"><b>${escapeText(text.slice(s.start,s.end))}</b><small>B${s.bulb} / E${s.erosion||0} / D${s.damage} / K${s.kerning||0}</small><button type="button" data-remove="${i}" aria-label="Remove treatment">×</button></span>`).join(''):'<span class="empty-selection">No marked letters</span>';document.querySelectorAll('[data-edit]').forEach(chip=>chip.addEventListener('click',()=>{activeSelection=Number(chip.dataset.edit);pendingRange=null;setTreatmentControls(selections[activeSelection]);renderSelections();renderSource();updateMeta('TREATMENT ACTIVE')}));document.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',event=>{event.stopPropagation();const index=Number(btn.dataset.remove);selections.splice(index,1);activeSelection=activeSelection===index?-1:activeSelection>index?activeSelection-1:activeSelection;renderSelections();renderSource()}))}
$('#text').addEventListener('select',event=>{const field=event.currentTarget;if(field.selectionStart!==field.selectionEnd){pendingRange={start:field.selectionStart,end:field.selectionEnd};activeSelection=-1;renderSelections();renderSource();updateMeta('LIVE SELECTION')}});
$('#selectionFont').addEventListener('change',event=>{if(activeSelection>=0){selections[activeSelection].font=event.target.value;renderSelections()}renderSource()});
$('#markSelection').addEventListener('click',()=>{const field=$('#text'),range=pendingRange||{start:field.selectionStart,end:field.selectionEnd};if(range.start===range.end){updateMeta('SELECT LETTERS FIRST');field.focus();return}selections.push({...range,bulb:val('selectionBulb'),erosion:val('selectionErosion'),damage:val('selectionDamage'),kerning:val('selectionKerning'),font:$('#selectionFont').value});activeSelection=selections.length-1;pendingRange=null;renderSelections();renderSource();field.setSelectionRange(range.end,range.end);field.blur();updateMeta('TREATMENT LOCKED')});
$('#copy').addEventListener('click',()=>copy(false));$('#copyOfCopy').addEventListener('click',()=>copy(true));$('#randomize').addEventListener('click',randomize);$('#export').addEventListener('click',()=>{const canvas=current||source,a=document.createElement('a');a.download=`copyshop-${$('#seed').value}-g${generation}.png`;a.href=canvas.toDataURL('image/png');a.click()});
function reconcileSelections(oldText,newText){let prefix=0;while(prefix<oldText.length&&prefix<newText.length&&oldText[prefix]===newText[prefix])prefix++;let suffix=0;while(suffix<oldText.length-prefix&&suffix<newText.length-prefix&&oldText[oldText.length-1-suffix]===newText[newText.length-1-suffix])suffix++;const oldEnd=oldText.length-suffix,newEnd=newText.length-suffix,delta=newEnd-oldEnd,pureInsert=oldEnd===prefix&&newEnd>prefix;selections=selections.map(s=>{if(pureInsert){if(s.end<=prefix)return s;if(s.start>=prefix)return{...s,start:s.start+delta,end:s.end+delta};return{...s,end:s.end+delta}}if(s.end<=prefix)return s;if(s.start>=oldEnd)return{...s,start:s.start+delta,end:s.end+delta};return{...s,start:Math.min(s.start,prefix),end:Math.max(prefix,Math.min(newEnd,s.end+delta))}}).filter(s=>s.end>s.start);if(activeSelection>=selections.length)activeSelection=selections.length-1}
$('#text').addEventListener('input',event=>{const newText=event.currentTarget.value;reconcileSelections(previousText,newText);previousText=newText;pendingRange=null;renderSelections();renderSource()});['font','align'].forEach(id=>$('#'+id).addEventListener('change',renderSource));$('#seed').addEventListener('input',()=>updateMeta('SEED CHANGED'));renderSource();copy(false);
