import{CopyEngine}from'./degradation-engine.js';
const $=s=>document.querySelector(s),engine=new CopyEngine(),source=$('#sourceCanvas'),result=$('#resultCanvas');let current=null,generation=0;
const typeDefs=[['size','SIZE',94,24,180,'px'],['leading','LEADING',92,70,150,'%'],['tracking','TRACKING',0,-8,30,'px'],['width','WIDTH',980,500,1400,'px'],['padding','PADDING',90,20,220,'px']];
const machineDefs=[['threshold','CONTRAST / THRESHOLD',53,0,100,''],['tonerDensity','TONER DENSITY',58,0,100,''],['inkBleed','INK BLEED',22,0,100,''],['erosion','EROSION',12,0,100,''],['dropout','DROPOUT',16,0,100,''],['edgeRoughness','EDGE ROUGHNESS',27,0,100,''],['grain','GRAIN',24,0,100,''],['localDistortion','LOCAL DISTORTION',10,0,100,''],['characterFailure','CHARACTER FAILURE',8,0,100,''],['copyCount','GENERATIONAL COPY COUNT',1,1,8,'×']];
function controls(target,defs){target.innerHTML=defs.map(([id,label,val,min,max,unit])=>`<label class="slider-row" for="${id}"><span>${label}</span><input id="${id}" type="range" min="${min}" max="${max}" value="${val}"><output id="${id}Out">${val}${unit}</output></label>`).join('');defs.forEach(([id,,, , ,unit])=>$('#'+id).addEventListener('input',e=>{$('#'+id+'Out').value=e.target.value+unit;if(typeDefs.some(d=>d[0]===id))renderSource()}))}
controls($('#typeControls'),typeDefs);controls($('#machineControls'),machineDefs);
function val(id){return Number($('#'+id).value)}function options(pass){return{seed:$('#seed').value||'copyshop',pass,threshold:val('threshold'),contrast:val('threshold'),tonerDensity:val('tonerDensity'),inkBleed:val('inkBleed'),erosion:val('erosion'),dropout:val('dropout'),edgeRoughness:val('edgeRoughness'),grain:val('grain'),localDistortion:val('localDistortion'),characterFailure:val('characterFailure')}}
function wrapText(ctx,text,maxWidth,tracking){const lines=[];for(const paragraph of text.split('\n')){const words=paragraph.split(/\s+/);let line='';for(const word of words){const test=line?line+' '+word:word;const measured=ctx.measureText(test).width+Math.max(0,test.length-1)*tracking;if(measured>maxWidth&&line){lines.push(line);line=word}else line=test}lines.push(line)}return lines}
function drawTracked(ctx,text,x,y,tracking,align){const widths=[...text].map(c=>ctx.measureText(c).width),total=widths.reduce((a,b)=>a+b,0)+tracking*Math.max(0,text.length-1);let cursor=align==='center'?x-total/2:align==='right'?x-total:x;for(let i=0;i<text.length;i++){ctx.fillText(text[i],cursor,y);cursor+=widths[i]+tracking}}
function renderSource(){const width=val('width'),pad=val('padding'),size=val('size'),leading=size*val('leading')/100,tracking=val('tracking'),font=$('#font').value,align=$('#align').value,ctx=source.getContext('2d');ctx.font=`900 ${size}px "${font}"`;const lines=wrapText(ctx,$('#text').value,width-pad*2,tracking),height=Math.max(700,Math.ceil(pad*2+lines.length*leading));source.width=width;source.height=height;ctx.fillStyle='#f6f6f1';ctx.fillRect(0,0,width,height);ctx.fillStyle='#111';ctx.font=`900 ${size}px "${font}"`;ctx.textBaseline='top';const x=align==='center'?width/2:align==='right'?width-pad:pad;lines.forEach((line,i)=>drawTracked(ctx,line,x,pad+i*leading,tracking,align));$('#dimensions').textContent=`${width} × ${height} PX`;current=null;generation=0;updateMeta('SOURCE READY')}
function copy(useCurrent=false){$('#status').textContent='PROCESSING';requestAnimationFrame(()=>{let input=useCurrent&&current?current:source;const passes=val('copyCount');for(let p=0;p<passes;p++)input=engine.process(input,options(generation+p+1));current=input;result.width=input.width;result.height=input.height;result.getContext('2d').drawImage(input,0,0);generation+=passes;updateMeta(useCurrent?'COPY OF COPY':'COPY COMPLETE')})}
function updateMeta(status){$('#status').textContent=status;$('#generation').textContent=String(generation).padStart(2,'0');$('#seedReadout').textContent=$('#seed').value;$('#resultLabel').textContent=generation?`generation ${generation}`:'awaiting copy'}
function randomize(){const rng=()=>Math.random();machineDefs.forEach(([id,,,min,max,unit])=>{if(id==='copyCount')return;const n=Math.round(min+rng()*(max-min));$('#'+id).value=n;$('#'+id+'Out').value=n+unit});$('#seed').value=Math.random().toString(36).slice(2,10);updateMeta('SETTINGS RANDOMIZED')}
$('#copy').addEventListener('click',()=>copy(false));$('#copyOfCopy').addEventListener('click',()=>copy(true));$('#randomize').addEventListener('click',randomize);$('#export').addEventListener('click',()=>{const canvas=current||source,a=document.createElement('a');a.download=`copyshop-${$('#seed').value}-g${generation}.png`;a.href=canvas.toDataURL('image/png');a.click()});['text','font','align'].forEach(id=>$('#'+id).addEventListener(id==='text'?'input':'change',renderSource));$('#seed').addEventListener('input',()=>updateMeta('SEED CHANGED'));renderSource();copy(false);
