export function seededRandom(seed='copyshop'){let h=2166136261;for(let i=0;i<seed.length;i++){h^=seed.charCodeAt(i);h=Math.imul(h,16777619)}return()=>{h+=0x6d2b79f5;let t=h;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
const clamp=v=>Math.max(0,Math.min(255,v));
function mono(data){const out=new Float32Array(data.length/4);for(let i=0,j=0;i<data.length;i+=4,j++)out[j]=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2];return out}
function morph(src,w,h,r,dilate){if(r<1)return src;const out=new Float32Array(src.length),rr=Math.min(4,Math.ceil(r));for(let y=0;y<h;y++)for(let x=0;x<w;x++){let v=dilate?255:0;for(let oy=-rr;oy<=rr;oy++)for(let ox=-rr;ox<=rr;ox++){const xx=Math.max(0,Math.min(w-1,x+ox)),yy=Math.max(0,Math.min(h-1,y+oy)),p=src[yy*w+xx];v=dilate?Math.min(v,p):Math.max(v,p)}out[y*w+x]=v}return out}
function blur(src,w,h,r){if(r<.3)return src;const rad=Math.min(5,Math.ceil(r)),tmp=new Float32Array(src.length),out=new Float32Array(src.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let s=0,n=0;for(let k=-rad;k<=rad;k++){s+=src[y*w+Math.max(0,Math.min(w-1,x+k))];n++}tmp[y*w+x]=s/n}for(let y=0;y<h;y++)for(let x=0;x<w;x++){let s=0,n=0;for(let k=-rad;k<=rad;k++){s+=tmp[Math.max(0,Math.min(h-1,y+k))*w+x];n++}out[y*w+x]=s/n}return out}
function smoothNoise(w,h,rng,scale){const gw=Math.ceil(w/scale)+2,gh=Math.ceil(h/scale)+2,g=new Float32Array(gw*gh);for(let i=0;i<g.length;i++)g[i]=rng();const out=new Float32Array(w*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const fx=x/scale,fy=y/scale,ix=Math.floor(fx),iy=Math.floor(fy),tx=fx-ix,ty=fy-iy,a=g[iy*gw+ix],b=g[iy*gw+ix+1],c=g[(iy+1)*gw+ix],d=g[(iy+1)*gw+ix+1];out[y*w+x]=(a*(1-tx)+b*tx)*(1-ty)+(c*(1-tx)+d*tx)*ty}return out}
export class CopyEngine{
  process(source,options={}){const w=source.width,h=source.height,ctx=source.getContext('2d',{willReadFrequently:true}),img=ctx.getImageData(0,0,w,h),rng=seededRandom(`${options.seed}|${options.pass||1}`);let px=mono(img.data);const density=options.tonerDensity??50,erosion=options.erosion??0,bleed=options.inkBleed??0;
    const rounding=options.cornerRoundness??0;if(rounding>0){px=blur(px,w,h,rounding/18);const cutoff=128-rounding*.035;for(let i=0;i<px.length;i++)px[i]=px[i]<cutoff?0:255}if(bleed>0)px=morph(px,w,h,bleed/28,true);if(erosion>0)px=morph(px,w,h,erosion/26,false);px=blur(px,w,h,bleed/45);
    const field=smoothNoise(w,h,rng,Math.max(12,70-(options.localDistortion||0)*.55)),grain=options.grain||0,rough=options.edgeRoughness||0,drop=options.dropout||0,dist=(options.localDistortion||0)/20,out=new Uint8ClampedArray(img.data.length),threshold=70+(options.threshold||50)*1.55;
    for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x,warp=Math.round((field[i]-.5)*dist),sx=Math.max(0,Math.min(w-1,x+warp)),sy=Math.max(0,Math.min(h-1,y+Math.round((field[i]-.5)*dist*.35))),si=sy*w+sx;let v=px[si];const edge=Math.abs(px[si]-px[Math.max(0,si-1)])+Math.abs(px[si]-px[Math.max(0,si-w)]);v+=(rng()-.5)*grain*1.8+(field[i]-.5)*rough*1.4;if(edge>24)v+=(rng()-.5)*rough*2.5;const inkChance=Math.max(0,(145-v)/145);if(rng()<drop*.00042*(.25+inkChance))v=255;v=(v-threshold)*((options.contrast||50)/18+1)+128;v-= (density-50)*1.25;v=v<128?Math.max(0,v-25):Math.min(255,v+20);const j=i*4;out[j]=out[j+1]=out[j+2]=clamp(v);out[j+3]=255}
    this.characterFailures(out,w,h,rng,options.characterFailure||0);const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').putImageData(new ImageData(out,w,h),0,0);return canvas}
  characterFailures(data,w,h,rng,amount){const count=Math.floor(amount/9);for(let n=0;n<count;n++){const rw=Math.floor(w*(.015+rng()*.06)),rh=Math.floor(h*(.018+rng()*.10)),x=Math.floor(rng()*(w-rw)),y=Math.floor(rng()*(h-rh)),mode=rng();for(let yy=y;yy<y+rh;yy++)for(let xx=x;xx<x+rw;xx++){const i=(yy*w+xx)*4;if(mode<.55&&rng()<.72)data[i]=data[i+1]=data[i+2]=255;else if(mode<.8&&rng()<.5)data[i]=data[i+1]=data[i+2]=0;else{const src=(yy*w+Math.max(0,xx-Math.floor(rw*.22)))*4;data[i]=data[i+1]=data[i+2]=data[src]}}}}
}
